[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "training-data-bot"
version = "0.1.0"
description = "Enterprise-grade training data curation bot for LLM fine-tuning"
authors = [{name = "Training Data Bot Team", email = "team@company.com"}]
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
keywords = ["llm", "training-data", "curation", "ai", "machine-learning"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    # Core dependencies
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "python-dotenv>=1.0.0",
    "typer[all]>=0.9.0",
    "rich>=13.0.0",
    "loguru>=0.7.0",
    
    # HTTP and async
    "httpx>=0.25.0",
    "aiohttp>=3.8.0",
    "requests>=2.31.0",
    "tenacity>=8.2.0",
    
    # Data processing
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "datasets>=2.14.0",
    "jsonlines>=4.0.0",
    
    # NLP and text processing
    "spacy>=3.6.0",
    "nltk>=3.8.0",
    "sentence-transformers>=2.2.0",
    "transformers>=4.30.0",
    "tokenizers>=0.13.0",
    
    # Document processing
    "PyMuPDF>=1.23.0",
    "python-docx>=0.8.11",
    "pdfminer.six>=20221105",
    "beautifulsoup4>=4.12.0",
    "markdownify>=0.11.6",
    "python-magic>=0.4.27",
    
    # Web scraping
    "selenium>=4.10.0",
    "playwright>=1.35.0",
    "scrapy>=2.9.0",
    
    # Quality checks and evaluation
    "detoxify>=0.5.2",
    "faiss-cpu>=1.7.4",
    "scikit-learn>=1.3.0",
    
    # Configuration and templates
    "jinja2>=3.1.0",
    "hydra-core>=1.3.0",
    "omegaconf>=2.3.0",
    "pyyaml>=6.0",
    
    # Dashboard and visualization
    "streamlit>=1.25.0",
    "plotly>=5.15.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    
    # Database and storage
    "sqlalchemy>=2.0.0",
    "alembic>=1.11.0",
    "redis>=4.6.0",
    
    # Testing and development
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.4.0",
    
    # Security
    "cryptography>=41.0.0",
    "bcrypt>=4.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.4.0",
    "pre-commit>=3.3.0",
]

gpu = [
    "faiss-gpu>=1.7.4",
    "torch>=2.0.0",
]

all = [
    "training-data-bot[dev,gpu]"
]

[project.scripts]
tdb = "training_data_bot.cli:app"
training-data-bot = "training_data_bot.cli:app"

[project.urls]
Homepage = "https://github.com/company/training-data-bot"
Documentation = "https://training-data-bot.readthedocs.io"
Repository = "https://github.com/company/training-data-bot"
Issues = "https://github.com/company/training-data-bot/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=training_data_bot --cov-report=html --cov-report=term-missing"

[tool.coverage.run]
source = ["src/training_data_bot"]
omit = ["*/tests/*", "*/venv/*", "*/__pycache__/*"] 